#### Raviteja Padala
<img align="left" img src= in.png height = 20 width="20"/>   https://www.linkedin.com/in/raviteja-padala/ <br>

<img align="left" img src= github.png height = 20 width="20"/> https://github.com/raviteja-padala


# <span style='color:Blue'> Objective :  </span> To know, understand and perform A/B testing on Screengaurd suggestion data.

### * Goal : To increase sales of mobile Screengaurds.

### * Hypothesis to check:  " Will suggestion type have impact on Screengaurd sales. i.e., will screen guards sell more when they are bundled or suggested with a mobile phone or when they are bundled or suggested with a mobile case." 

In [2]:
#import libraries
import pandas as pd

In [3]:
#import data
df = pd.read_csv("https://raw.githubusercontent.com/raviteja-padala/Datasets/main/Screengaurd_Recommendation_data.csv")
df.head()

customer_id    Recommendation_name Recommendation_date suggestion_type  \
0          1.0  Recommend_screenguard          02-07-2021      With phone   
1          2.0  Recommend_screenguard          03-07-2021      With phone   
2          3.0  Recommend_screenguard          04-07-2021      With cover   
3          4.0  Recommend_screenguard          05-07-2021      With phone   
4          5.0  Recommend_screenguard          06-07-2021      With cover   

   purchase_flag  
0            0.0  
1            0.0  
2            1.0  
3            0.0  
4            1.0

* About dataset: 

> The dataset includes ,customer_id ,	Recommendation_name,	Recommendation_date	,suggestion_type ,	purchase_flag.<br>
> - Suggestion type means The Screean gaurd is suggested with Phone or with Cover.<br>
> - purchase_flag includes 0 means not sold, 1 indicates sold

In [5]:
#shape of dataset

df.shape

(870, 5)

In [9]:
#checking for null values

df.isnull().sum()

customer_id            159
Recommendation_name    159
Recommendation_date    159
suggestion_type        159
purchase_flag          159
dtype: int64

In [10]:
#dropping null values

df.dropna(inplace =True)

In [11]:
#shape of dataset after dropping null values

df.shape

(711, 5)

In [14]:
#checking count in each category
df.groupby( "suggestion_type" )[ "purchase_flag" ].value_counts()

suggestion_type  purchase_flag
With cover       0.0              206
                 1.0              130
With phone       0.0              258
                 1.0              117
Name: purchase_flag, dtype: int64

<span style='color:Blue'> **Observation:** </span> 
 
As per above group by data , we can observe that Screegaurd is sold 130 times when recommended with Cover, and Sold 117 times when recommended with phone.

#### Contingency Table is one of the techniques for exploring two or even more variables. It is basically a tally of counts between two or more categorical variables.

In [17]:
#Contingency Table
contingency_data = pd.crosstab(df['suggestion_type'],df['purchase_flag'])
contingency_data

purchase_flag    0.0  1.0
suggestion_type          
With cover       206  130
With phone       258  117

In [22]:
# compute screen gaurd purchase rate with phone and with cover


with_phone_rate = 117 / (117 + 258)

with_cover_rate = 130 / (206 + 130)


print(f"Purchase rate with phone is= {with_phone_rate}, Purchase rate with cover is {with_cover_rate}")

Purchase rate with phone is= 0.312, Purchase rate with cover is 0.3869047619047619


#### Hypothesis: 

* Null hypothesis:  independent categories:There is no relationship between Purchase rate and Suggestion type

* Alternate Hypothesis: dependent categories:There is significant relationship between Purchase rate and Suggestion type

In [24]:
#chi square test
from scipy.stats import chi2_contingency

test_stat, p_value, dof, expected = chi2_contingency(contingency_data)

print('Test statistic=%.3f, p_values=%.3f, degrees_of_freedom=%s' % (test_stat, p_value,dof))

if p_value > 0.05:
    print('independent categories:There is no relationship between Purchase rate and Suggestion type')
else:
    print('dependent categories:There is significant relationship between Purchase rate and Suggestion type')

Test statistic=4.062, p_values=0.044, degrees_of_freedom=1
dependent categories:There is significant relationship between Purchase rate and Suggestion type


<span style='color:Blue'> **Observation:** </span> 

As per the above statistical test we can observe that Suggestion type has impact on sales of screen gaurd.

### Conclusion: We have performed A/B testing on given data and observed that Suggestion type has significant impact on sales of screengaurd, thus by increasing screangaurd suggestion with cover will increase more sales of screengaurd. Thank you for reading all the way to the end.